name: sgp_gen
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.10
  - cuda-toolkit=12.4
  - pycairo
  - ipykernel
  - cairo
  - pkg-config
  - cairosvg
  - xorg-libx11
  - xorg-libxext
  - xorg-libxcb
  - xorg-libxrender
